<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-12-07 21:45

$extensionPath = t3lib_extMgm::extPath('sitemgr_template');
$extensionClassesPath = t3lib_extMgm::extPath('sitemgr_template') . 'Classes/';
return array(
	'tx_sitemgrtemplate_domain_model_templateabstractmodel' => $extensionClassesPath . 'Domain/Model/TemplateAbstractModel.php',
	'tx_sitemgrtemplate_domain_model_templateoldsitemgrmodel' => $extensionClassesPath . 'Domain/Model/TemplateOldsitemgrModel.php',
	'tx_sitemgrtemplate_domain_model_templatetemplavoilaframeworkmodel' => $extensionClassesPath . 'Domain/Model/TemplateTemplavoilaFrameworkModel.php',
	'tx_sitemgrtemplate_domain_model_templatetemplavoilamodel' => $extensionClassesPath . 'Domain/Model/TemplateTemplavoilaModel.php',
	'tx_sitemgrtemplate_domain_repository_templateabstractrepository' => $extensionClassesPath . 'Domain/Repository/TemplateAbstractRepository.php',
	'tx_sitemgrtemplate_domain_repository_templaterepository' => $extensionClassesPath . 'Domain/Repository/TemplateRepository.php',
	'tx_sitemgrtemplate_domain_repository_templatetemplavoilaframeworkrepository' => $extensionClassesPath . 'Domain/Repository/TemplateTemplavoilaFrameworkRepository.php',
	'tx_sitemgrtemplate_domain_repository_templatetemplavoilarepository' => $extensionClassesPath . 'Domain/Repository/TemplateTemplavoilaRepository.php',
	'tx_sitemgrtemplate_modules_template_templatecontroller' => $extensionClassesPath . 'Modules/Template/TemplateController.php',
);
?>